// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type DistillationItem struct {
	ID                  int64
	SourceType          string
	DocID               string
	Url                 string
	License             string
	Title               string
	Locator             string
	SourceExcerpt       string
	RetrievedAt         *time.Time
	QueuedAt            *time.Time
	ComprehendedAt      *time.Time
	QuestionedAt        *time.Time
	PresolvedAt         *time.Time
	AnsweredAt          *time.Time
	VerifiedAt          *time.Time
	ProjectedAt         *time.Time
	SupersededAt        *time.Time
	FailedAt            *time.Time
	FailStage           string
	FailReason          string
	RetryCount          int32
	NextAttemptAt       *time.Time
	LastError           string
	LockOwnerID         pgtype.Text
	LockAt              *time.Time
	ComprehensionDigest pgtype.Text
	Question            []byte
	PresolveVerdict     []byte
	AnswerPayload       []byte
	Verification        []byte
}

type DistillationPair struct {
	ID                   int32
	TaskID               string
	Domain               string
	Difficulty           string
	TaskShape            string
	CapabilityTags       []string
	UserRequest          string
	Context              string
	SuccessCriteria      []string
	Plan                 []string
	ReasoningSummary     string
	FinalAnswer          string
	SelfCheck            []string
	QualityNotes         []string
	References           []string
	Artifacts            []string
	SourceLane           pgtype.Text
	PairID               pgtype.Text
	ArtifactRefs         []byte
	StudentFilterVerdict []byte
	Verification         []byte
	DifficultyMutations  []string
	TeacherModel         pgtype.Text
	TeacherProvider      pgtype.Text
	Cot                  pgtype.Text
	CotRaw               pgtype.Text
	HasRawCot            pgtype.Bool
	CreatedAt            *time.Time
}

type DistillationSourceCursor struct {
	SourceType string
	Position   string
	UpdatedAt  pgtype.Timestamptz
}
