// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: queries.sql

package sqlcgen

import (
	"context"
	"time"
)

const countPairs = `-- name: CountPairs :one

SELECT COUNT(*) FROM distillation_pairs
`

// === distillation_pairs buffer ===
// CountPairs returns the number of buffered rows (flush threshold check).
func (q *Queries) CountPairs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPairs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePairsByTaskIDs = `-- name: DeletePairsByTaskIDs :execrows
DELETE FROM distillation_pairs WHERE task_id = ANY($1::text[])
`

// DeletePairsByTaskIDs clears exactly the exported rows, keyed by the unique
// task_id (not id <= maxID) to close the flush TOCTOU window. :execrows returns
// the delete count.
func (q *Queries) DeletePairsByTaskIDs(ctx context.Context, taskIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePairsByTaskIDs, taskIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueue = `-- name: Enqueue :execrows


INSERT INTO distillation_items (
    source_type, doc_id, url, license, title, locator, retrieved_at, source_excerpt, queued_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (source_type, doc_id) DO NOTHING
`

type EnqueueParams struct {
	SourceType    string
	DocID         string
	Url           string
	License       string
	Title         string
	Locator       string
	RetrievedAt   *time.Time
	SourceExcerpt string
}

// Consolidated static queries for the pipeline persistence layer, generated by
// sqlc (out: sqlcgen) from the schema in migrations/. The generated code is
// wrapped by hand-written methods whose public signatures stay unchanged:
// internal/queue Store (Enqueue/GetCursor/SaveCursor) and internal/loader
// (CountRows/MaxID/DeleteByTaskIDs).
//
// Two statement families deliberately stay hand-written and are NOT here:
//   - queue dynamic per-stage transitions (claim/complete/fail/retry/supersede)
//     interpolate the stage's timestamp column (stageMeta.doneCol / .prev) at
//     runtime, which sqlc's static model cannot express -- see queue/claim.go.
//   - loader InsertRecord takes an untyped map[string]any through a signature two
//     frozen callers depend on (internal/runner, internal/worker), and
//     internal/runner/runner_test.go asserts strings.HasPrefix(TrimSpace(sql),
//     "INSERT"), which sqlc's mandatory leading "-- name: ..." comment would
//     break -- see loader/loader.go (insertSQL).
//
// === queue state machine ===
// Enqueue registers one ingested source document at the queued_at state, or does
// nothing on a (source_type, doc_id) collision (ingest idempotency). :execrows
// returns the affected-row count so the caller reports inserted (rows>0) vs
// duplicate (rows=0). queued_at is stamped NOW().
func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueue,
		arg.SourceType,
		arg.DocID,
		arg.Url,
		arg.License,
		arg.Title,
		arg.Locator,
		arg.RetrievedAt,
		arg.SourceExcerpt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCursor = `-- name: GetCursor :one
SELECT position FROM distillation_source_cursors WHERE source_type = $1
`

// GetCursor reads the opaque ingest position for a source (pgx.ErrNoRows when the
// source has never been ingested; the caller maps that to "").
func (q *Queries) GetCursor(ctx context.Context, sourceType string) (string, error) {
	row := q.db.QueryRow(ctx, getCursor, sourceType)
	var position string
	err := row.Scan(&position)
	return position, err
}

const maxPairID = `-- name: MaxPairID :one
SELECT COALESCE(MAX(id), 0)::bigint FROM distillation_pairs
`

// MaxPairID returns the high-water mark id (0 when empty), snapshotted at flush
// start. Cast to bigint so the Go type is int64 (id is SERIAL/int4).
func (q *Queries) MaxPairID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxPairID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const saveCursor = `-- name: SaveCursor :exec
INSERT INTO distillation_source_cursors (source_type, position, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (source_type) DO UPDATE SET position = EXCLUDED.position, updated_at = now()
`

type SaveCursorParams struct {
	SourceType string
	Position   string
}

// SaveCursor upserts the opaque ingest watermark for a source.
func (q *Queries) SaveCursor(ctx context.Context, arg SaveCursorParams) error {
	_, err := q.db.Exec(ctx, saveCursor, arg.SourceType, arg.Position)
	return err
}
