-- Consolidated static queries for the pipeline persistence layer, generated by
-- sqlc (out: sqlcgen) from the schema in migrations/. The generated code is
-- wrapped by hand-written methods whose public signatures stay unchanged:
-- internal/queue Store (Enqueue/GetCursor/SaveCursor) and internal/loader
-- (CountRows/MaxID/DeleteByTaskIDs).
--
-- Two statement families deliberately stay hand-written and are NOT here:
--   * queue dynamic per-stage transitions (claim/complete/fail/retry/supersede)
--     interpolate the stage's timestamp column (stageMeta.doneCol / .prev) at
--     runtime, which sqlc's static model cannot express -- see queue/claim.go.
--   * loader InsertRecord takes an untyped map[string]any through a signature two
--     frozen callers depend on (internal/runner, internal/worker), and
--     internal/runner/runner_test.go asserts strings.HasPrefix(TrimSpace(sql),
--     "INSERT"), which sqlc's mandatory leading "-- name: ..." comment would
--     break -- see loader/loader.go (insertSQL).

-- === queue state machine ===

-- Enqueue registers one ingested source document at the queued_at state, or does
-- nothing on a (source_type, doc_id) collision (ingest idempotency). :execrows
-- returns the affected-row count so the caller reports inserted (rows>0) vs
-- duplicate (rows=0). queued_at is stamped NOW().
-- name: Enqueue :execrows
INSERT INTO distillation_items (
    source_type, doc_id, url, license, title, locator, retrieved_at, source_excerpt, queued_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (source_type, doc_id) DO NOTHING;

-- GetCursor reads the opaque ingest position for a source (pgx.ErrNoRows when the
-- source has never been ingested; the caller maps that to "").
-- name: GetCursor :one
SELECT position FROM distillation_source_cursors WHERE source_type = $1;

-- SaveCursor upserts the opaque ingest watermark for a source.
-- name: SaveCursor :exec
INSERT INTO distillation_source_cursors (source_type, position, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (source_type) DO UPDATE SET position = EXCLUDED.position, updated_at = now();

-- === distillation_pairs buffer ===

-- CountPairs returns the number of buffered rows (flush threshold check).
-- name: CountPairs :one
SELECT COUNT(*) FROM distillation_pairs;

-- MaxPairID returns the high-water mark id (0 when empty), snapshotted at flush
-- start. Cast to bigint so the Go type is int64 (id is SERIAL/int4).
-- name: MaxPairID :one
SELECT COALESCE(MAX(id), 0)::bigint FROM distillation_pairs;

-- DeletePairsByTaskIDs clears exactly the exported rows, keyed by the unique
-- task_id (not id <= maxID) to close the flush TOCTOU window. :execrows returns
-- the delete count.
-- name: DeletePairsByTaskIDs :execrows
DELETE FROM distillation_pairs WHERE task_id = ANY(@task_ids::text[]);
